### ISSUE TITLE
Loadout changes / loadouts at beginning

### ISSUE THREAD

**Issue by Okimoka** [demostf/demo.js#1]
Where's the data saved which tells what weapons (or even cosmetics) the players have equipped, before they actually kill something? When watching the demo, you always spawn with the correct weapon in the hand.
Similarily, when do you know that a player has changed their weapon?

**Comment by icewind1991** [comment]
With eebc2e15cd0d49aeca68d3c35ca1e1dba4cd50f5 you can get a players weapon info using `Player.weapons` and `Player.activeWeapon`

```typescript
const Demo = getDemoFromSomewhere();
const parser = demo.getParser();
parser.readHeader();
const match = parser.match;
let lastTick = 0;
parser.on('packet', (packet: Packet) => {
	if(match.stick>lastTick){
		lastTick = match.tick;
		for (const player of match.players) {
			console.log(player.weapons[player.activeWeapon].className);
		}
	}
});
parser.parseBody();
```
