### ISSUE TITLE
Broken with demos recorded post-MyM

### ISSUE THREAD

**Issue by tcmal** [demostf/demo.js#2]
index.js
```
var Demo = require('tf2-demo');
var fs = require('fs');

fs.readFile(process.argv[1], function (err, data) {
	if (err) throw err;
	var demo = Demo.fromNodeBuffer(data);
	var parser = demo.getParser();
	
	var head = parser.readHeader();
	var body = parser.parseBody();
	
	console.log(head);
	console.log(body);
});
```

Running:
```
 $ node index.js 2016-12-10_14-20-18.dem
/home/oscar/Projects/TF2/demosup-parser/node_modules/bit-buffer/bit-buffer.js:58
		throw new Error('Cannot get ' + bits + ' bit(s) from offset ' + offset + ', ' + available + ' available');
		^

Error: Cannot get 8 bit(s) from offset 15620261096, -15620239832 available
    at BitView.getBits (/home/oscar/Projects/TF2/demosup-parser/node_modules/bit-buffer/bit-buffer.js:58:9)
    at BitStream.readBits (/home/oscar/Projects/TF2/demosup-parser/node_modules/bit-buffer/bit-buffer.js:329:23)
    at Parser.readMessage (/home/oscar/Projects/TF2/demosup-parser/node_modules/tf2-demo/parser.js:98:20)
    at Parser.parseBody (/home/oscar/Projects/TF2/demosup-parser/node_modules/tf2-demo/parser.js:56:24)
    at /home/oscar/Projects/TF2/demosup-parser/index.js:10:20
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:415:3)
```

with [this demo](https://mega.nz/#!KpM1wJrC!WlbZBpBKKiVKnfACGAow1Pqi0NApzZ-6h_R7FUhn9tY)

Is this package supported anymore?

**Comment by icewind1991** [comment]
This project is mostly focused on parsing stv demos as that is my main use case for this and thus pov demos have always been a second class citizen and parsing them is a lot more error prone.

That said, I've made some updates to mostly work around the error so it can at least finish parsing the demo. With those "fixes" it doesn't get all the player names (about half of them end up with `null`) but most other things like kills and rounds seem to be correct.

You can try these changes by downloading the plugin from git and building it by running from the demo.js folder:

```
make
```

if you have `make` installed on your system or

```
npm install --deps
node node_modules/.bin/tsc
```

**Comment by tcmal** [comment]
Make fails with `make: *** No targets specified and no makefile found.  Stop.` and .bin doesn't exist.

Running `node bin/analyse.js 2016-12-10_14-20-18.dem` still gives:

```
buffer.js:274
  throw new TypeError(kFromErrorMsg);
  ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:274:9)
    at Function.Buffer.from (buffer.js:106:10)
    at new Buffer (buffer.js:85:17)
    at BitStream.get [as buffer] (/home/oscar/Projects/TF2/demo.js/node_modules/bit-buffer/bit-buffer.js:314:28)
    at Parser.readMessage (/home/oscar/Projects/TF2/demo.js/parser.js:121:17)
    at Parser.parseBody (/home/oscar/Projects/TF2/demo.js/parser.js:56:24)
    at /home/oscar/Projects/TF2/demo.js/bin/analyse.js:33:20
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:415:3)
```

**Comment by gavvvr** [comment]
What is this issue about? What does **post-MyM** mean? I do not see any makefile or TypeScript presence in this module.
But i get the same error when try to use `analyse.js` providing sample STV demo:

> buffer.js:262
>   throw new TypeError(kFromErrorMsg);
>   ^
> 
> TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
>     at fromObject (buffer.js:262:9)
>     at Function.Buffer.from (buffer.js:101:10)
>     at new Buffer (buffer.js:80:17)
>     at BitStream.get [as buffer] (C:\Users\gavvv\Desktop\demo.js\node_modules\bit-buffer\bit-buffer.js:314:28)
>     at Parser.readMessage (C:\Users\gavvv\Desktop\demo.js\parser.js:121:17)
>     at Parser.parseBody (C:\Users\gavvv\Desktop\demo.js\parser.js:56:24)
>     at C:\Users\gavvv\Desktop\demo.js\bin\analyse.js:33:20
>     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)


Tried it with node 7,6,4.

With node 0.12 i get another error:

> C:\Users\gavvv\Desktop\demo.js\node_modules\bit-buffer\bit-buffer.js:53
>                 throw new Error('Cannot get ' + bits + ' bit(s) from offset ' + offset + ',
>                       ^
> Error: Cannot get 6 bit(s) from offset 0, 0 available
>     at BitView.getBits (C:\Users\gavvv\Desktop\demo.js\node_modules\bit-buffer\bit-buffer.js:53:9)
>     at BitStream.readBits (C:\Users\gavvv\Desktop\demo.js\node_modules\bit-buffer\bit-buffer.js:326:23)
>     at Packet.parse (C:\Users\gavvv\Desktop\demo.js\packet.js:31:26)
>     at Parser.handleMessage (C:\Users\gavvv\Desktop\demo.js\parser.js:87:25)
>     at Parser.parseBody (C:\Users\gavvv\Desktop\demo.js\parser.js:57:8)
>     at C:\Users\gavvv\Desktop\demo.js\bin\analyse.js:33:20
>     at fs.js:334:14
>     at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by tcmal** [comment]
post-MyM as in after the Meet your match update. It's probably something else though, Basically just recent demos.

**Comment by tcmal** [comment]
Bump. Works with STVs (random from demos.tf) but not with POVs.

`./bin/analyse.js ../demoparse/demo.dem`

```
/home/oscar/Projects/demo.js/src/PacketHandler/StringTable.ts:36
		throw new Error('Missing baseline');
        ^
Error: Missing baseline
    at saveInstanceBaseLine (/home/oscar/Projects/demo.js/src/PacketHandler/StringTable.ts:36:9)
    at Object.handleStringTable (/home/oscar/Projects/demo.js/src/PacketHandler/StringTable.ts:26:5)
    at Match.handlePacket (/home/oscar/Projects/demo.js/src/Data/Match.ts:132:5)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser.handleMessage (/home/oscar/Projects/demo.js/src/Parser.ts:84:11)
    at Parser.tick (/home/oscar/Projects/demo.js/src/Parser.ts:54:9)
    at Parser.parseBody (/home/oscar/Projects/demo.js/src/Parser.ts:45:19)
    at /home/oscar/Projects/demo.js/bin/analyse.js:37:21
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

[Demo file](https://mega.nz/#!nx8lwKhD!SNFT7f0VVuzVQp-OuBnPwaQrIyTc3aTT0ubVoWyjSfw)

**Comment by icewind1991** [comment]
Pushed some fixes for POV demos, it now successfully parses the few different POV demos I tried throwing at it

**Comment by tcmal** [comment]
No difference. The github still says 5 days ago, Is it a different branch?

**Comment by icewind1991** [comment]
forgot to push 🙈

**Comment by tcmal** [comment]
Nice. Also, Where do the classes field in each players come from? Does it only work on the local player's POV for POV demos? And what does the value correspond to?

**Comment by icewind1991** [comment]
Classes should work also for non-local players.

> And what does the value correspond to?

The keys of the `classes` object are the class ids[1], the values the number of time the player spawned as that class.

[1]: 
```
1: "scout",
2: "sniper",
3: "soldier",
4: "demoman",
5: "medic",
6: "heavy",
7: "pyro",
8: "spy",
9: "engineer"
```
