### ISSUE TITLE
What are those values in classes properties?

### ISSUE THREAD

**Issue by PabloDinella** [demostf/demo.js#6]
```
    "197": {
      "classes": {
        "1": 6,
        "4": 1,
        "7": 1,
        "9": 1
      },
      "name": "burg",
      "steamId": "[U:1:0000000]",
      "userId": 197,
      "team": "red"
    },
```
I infer that the `1`, `4`, `7`, and `9` in `classes` are Scout, Demoman, Medic and Spy respectively, is that right? And what about the values `6`, `1`, `1`, and `1`?

**Comment by icewind1991** [comment]
1: "scout",
2: "sniper",
3: "soldier",
4: "demoman",
5: "medic",
6: "heavy",
7: "pyro",
8: "spy",
9: "engineer"

The values are the number of times the player spawned as that class

**Comment by PabloDinella** [comment]
Thanks!
